#!/bin/sh
#
# This hook removes output from ipython notebooks before commit and
# depends on nbstripout https://github.com/kynan/nbstripout, which
# can be installed via pip or conda
#
# This hook will not be executed using default git configurations.
#
# To use this hook, execute:
# 	git config core.hooksPath shared_hooks

NBS=$(echo $(git diff --full-index -z --cached $against --name-only) | sort | grep "ipynb")

if [ ! -z "$NBS" ] ; then
	command -v nbstripout >/dev/null 2>&1 || { echo >&2 "I require nbstripout but it's not installed. Aborting commit."; exit 1; }
fi

for NB in $NBS ; do
    echo "Removing outputs from $NB"
    nbstripout $NB
    git add "$NB"
done

# If there are whitespace errors, print the offending file names and fail.
exec git diff --full-index --check --cached $against --
